import a from "../assets/alphabets/a.png"
import b from "../assets/alphabets/b.png"
import c from "../assets/alphabets/c.png"
import d from "../assets/alphabets/d.png"
import e from "../assets/alphabets/e.png"
import f from "../assets/alphabets/f.png"
import g from "../assets/alphabets/g.png"
import h from "../assets/alphabets/h.png"
import i from "../assets/alphabets/i.png"
import j from "../assets/alphabets/j.png"
import k from "../assets/alphabets/k.png"
import l from "../assets/alphabets/l.png"
import m from "../assets/alphabets/m.png"
import n from "../assets/alphabets/n.png"
import o from "../assets/alphabets/o.png"
import p from "../assets/alphabets/p.png"
import q from "../assets/alphabets/q.png"
import r from "../assets/alphabets/r.png"
import s from "../assets/alphabets/s.png"
import t from "../assets/alphabets/t.png"
import u from "../assets/alphabets/u.png"
import v from "../assets/alphabets/v.png"
import w from "../assets/alphabets/w.png"
import x from "../assets/alphabets/x.png"
import y from "../assets/alphabets/y.png"
import z from "../assets/alphabets/z.png"


export { a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z }